# === Shadows ===
shadow = true;
shadow-radius = 14;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.5;
shadow-exclude = [
    "name = 'Notification'",
    "class_g = 'Polybar'",
    "class_g = 'i3-frame'",
    "_GTK_FRAME_EXTENTS@:c"
];

# === Fading ===
fading = true;
fade-in-step = 0.06;
fade-out-step = 0.06;
fade-delta = 5;

# === Transparency ===
inactive-opacity = 0.90;
active-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

focus-exclude = [
    "class_g = 'Rofi'",
    "class_g = 'dmenu'"
];

# === Corners ===
corner-radius = 6;
rounded-corners-exclude = [ ];

# === General ===
backend = "glx";
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = true;
