# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        colors = true
        color_good = "#00A5FF" #some neon blue
        color_degraded = "#006298"
        color_bad = "#FF0000"
        interval = 5
        markup = "pango"
}

order += "cpu_usage"
order += "cpu_temperature 0"
order += "read_file FAN_SPEED"
order += "memory"
order += "read_file BAT_STATUS"
order += "volume master"
order += "read_file WEATHER"
order += "tztime local"



wireless _first_ {
        format_up = "🛜%quality %essid"
        format_down = "🛜❌"
}

ethernet _first_ {
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}

battery all {
        format =  "🔋 %status %percentage %remaining"
}

disk "/" {
        format = "%avail"
}

cpu_usage {
        format = "CPU:%usage"
} 

memory {
        format = "RAM:%percentage_used"
        memory_used_method = "memavailable"
        threshold_degraded = "10%"
        format_degraded = "MEM: %free"
}

tztime local {
        format = "🗓️%Y-%m-%d 🕒%H:%M:%S"
}

cpu_temperature 0{
        format = "🌡️%degrees°C"
        path = "/sys/class/thermal/thermal_zone0/temp"
}

volume master {
    format = "🔊%volume"
    format_muted = "🔈%volume"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

read_file OPENVPN {
    format = "%content"
    path = "/tmp/openvpn_config"
}

read_file BAT_STATUS {
    format = "%content"
    path = "/tmp/bat_status"
}

read_file FAN_SPEED {
    format = "🌀 %content RPM"
    path = "/tmp/fan_speed"
}


read_file WEATHER {
    format = "<span color='#FFFFFF'>%content</span>"
    path = "/tmp/get-my-weather.txt"
}

